// tests/unit/server/transcript-to-blocks.spec.ts
// Issue #39 (decision #26) — the transcript normalization suite. Pins the
// caption→paragraph char-budget grouping (~380 target / ~600 hard cap, never
// splitting a segment), the five chapter→h2 edge rules, and the block-keyed
// timestamp anchor map ({blockIndex, startMs}) that rides
// ingestionMeta.transcript — timestamps never enter block text.
import { describe, expect, it } from "vitest";
import { ArticleSchema, BlockSchema } from "../../../src/content/schema";
import { deriveToc } from "../../../src/content/toc";
import {
  TRANSCRIPT_PARAGRAPH_CAP_CHARS,
  TRANSCRIPT_PARAGRAPH_TARGET_CHARS,
  transcriptToBlocks,
} from "../../../server/transcriptToBlocks";
import type {
  TranscriptChapter,
  TranscriptSegment,
  TranscriptSuccess,
} from "../../../src/ingestion/youtube";

/** seg — one caption cue at a given time. */
function seg(text: string, startMs: number): TranscriptSegment {
  return { text, startMs, durationMs: 1000 };
}

/** ch — one creator chapter marker. */
function ch(title: string, startMs: number): TranscriptChapter {
  return { title, startMs };
}

/** success — a minimal valid TranscriptSuccess around the given segments. */
function success(
  segments: TranscriptSegment[],
  chapters: TranscriptChapter[] = [],
  title = "Never Gonna Give You Up",
): TranscriptSuccess {
  return {
    ok: true,
    videoId: "dQw4w9WgXcQ",
    title,
    channel: "Rick Astley",
    durationSeconds: 213,
    languageCode: "en",
    isAutoGenerated: false,
    segments,
    chapters,
  };
}

/** textOf — a block's normalized text contribution (runs joined). */
function textOf(block: { content: { text: string }[] }): string {
  return block.content.map((r) => r.text).join(" ");
}

/** words — deterministic pseudo-ASR text of an exact character length: a
 * repeated word pattern whose joined length is exactly `len` (never split,
 * so a lone cue of this length lands in ONE paragraph). */
function cue(len: number, seed = 0): string {
  const words = ["you", "know", "the", "rules", "and", "so", "do", "I"];
  const parts: string[] = [];
  let used = 0;
  let i = seed;
  while (used < len) {
    const word = words[i % words.length]!;
    const addition = used === 0 ? word.length : word.length + 1;
    if (used + addition > len) break;
    parts.push(word);
    used += addition;
    i += 1;
  }
  if (used < len) {
    // pad the remainder with 'x' + separators to hit the exact length
    const pad = len - used;
    parts.push("x".repeat(pad === 1 ? 1 : pad - 1));
    used = len;
  }
  return parts.join(" ");
}

describe("caption → paragraph grouping (char budgets)", () => {
  it("merges short cues into print-like paragraphs (manual per-line cues included)", () => {
    const result = transcriptToBlocks(
      success([seg("We're no strangers to love", 0), seg("You know the rules and so do I", 5000)]),
    );
    expect(result.blocks).toHaveLength(1);
    expect(result.blocks[0]!.kind).toBe("paragraph");
    expect(textOf(result.blocks[0] as { content: { text: string }[] })).toBe(
      "We're no strangers to love You know the rules and so do I",
    );
  });

  it("flushes at the ~380 target: the next segment starts a fresh paragraph", () => {
    // two ~200-char cues: the first stays under target, the second crosses
    // it → exactly two paragraphs, second joined after the crossing
    const a = cue(TRANSCRIPT_PARAGRAPH_TARGET_CHARS - 50, 0);
    const b = cue(60, 3);
    const c = cue(60, 5);
    const result = transcriptToBlocks(success([seg(a, 0), seg(b, 1000), seg(c, 2000)]));
    const paragraphs = result.blocks.filter((bl) => bl.kind === "paragraph");
    // a+b = target-50 + 61 ≥ target → flushed; c alone
    expect(paragraphs).toHaveLength(2);
  });

  it("hard cap ~600 forces a break BEFORE a segment that would push past it", () => {
    const a = cue(300, 0);
    const b = cue(350, 2); // 300 + 1 + 350 = 651 > 600
    const result = transcriptToBlocks(success([seg(a, 0), seg(b, 1000)]));
    expect(result.blocks).toHaveLength(2);
    expect(textOf(result.blocks[0] as { content: { text: string }[] })).toBe(a);
    expect(textOf(result.blocks[1] as { content: { text: string }[] })).toBe(b);
  });

  it("never splits a segment: a lone ~2000-char cue stays ONE paragraph", () => {
    const pathological = cue(2000, 0);
    expect(pathological.length).toBe(2000);
    const result = transcriptToBlocks(success([seg(pathological, 0)]));
    expect(result.blocks).toHaveLength(1);
    expect(textOf(result.blocks[0] as { content: { text: string }[] })).toBe(pathological);
  });

  it("keeps every paragraph at or under the hard cap except lone oversized cues", () => {
    const segments: TranscriptSegment[] = [];
    let t = 0;
    for (let i = 0; i < 200; i += 1) {
      segments.push(seg(cue(40 + (i % 7) * 30, i), t));
      t += 1000;
    }
    const result = transcriptToBlocks(success(segments));
    for (const block of result.blocks) {
      if (block.kind !== "paragraph") continue;
      const text = textOf(block);
      // ≤ cap, or the paragraph is a single unsplit cue (the only legal way
      // to exceed the cap)
      expect(text.length <= TRANSCRIPT_PARAGRAPH_CAP_CHARS || !text.includes(" ".repeat(2))).toBe(
        true,
      );
    }
  });

  it("drops whitespace-only cues (no readable text, no anchor) with a calm count warning", () => {
    const result = transcriptToBlocks(
      success([seg("real words here", 0), seg("   ", 1000), seg("more real words", 2000)]),
    );
    expect(result.blocks).toHaveLength(1);
    expect(textOf(result.blocks[0] as { content: { text: string }[] })).toBe(
      "real words here more real words",
    );
    // The drop is DISCLOSED, never silent (the honesty guardrail).
    expect(result.warnings).toEqual(["1 caption cue without readable text was omitted"]);
  });

  it("discloses an all-whitespace track while refusing (empty blocks + the count warning)", () => {
    const result = transcriptToBlocks(success([seg("  ", 0), seg("\n\t", 1000)]));
    expect(result.blocks).toHaveLength(0);
    expect(result.anchors).toHaveLength(0);
    expect(result.warnings).toEqual(["2 caption cues without readable text were omitted"]);
  });

  it("validates every emitted block against the canonical BlockSchema", () => {
    const result = transcriptToBlocks(
      success([seg(cue(100, 0), 0), seg(cue(100, 3), 1000)], [ch("Intro", 0)]),
    );
    for (const block of result.blocks) {
      expect(() => BlockSchema.parse(block)).not.toThrow();
    }
  });
});

describe("chapter → h2 edge rules (decision #26, all five)", () => {
  it("rule 1 — missing chapters: no h2 at all, plain paragraphs only", () => {
    const result = transcriptToBlocks(success([seg("a cue", 0), seg("another cue", 1000)]));
    expect(result.blocks.every((b) => b.kind === "paragraph")).toBe(true);
    expect(result.warnings).toEqual([]);
  });

  it("rule 1 downstream — a chapterless transcript's TOC honestly offers only 'Top of article'", () => {
    // The acceptance-criteria composition: normalizer output with zero
    // heading blocks derives a Top-only TOC (deriveToc D18-13) — the reading
    // surface never invents structure the transcript didn't carry.
    const result = transcriptToBlocks(success([seg("a cue", 0), seg("another cue", 1000)]));
    const article = ArticleSchema.parse({
      id: "transcript-rule-1",
      revision: 1,
      lang: "en",
      provenance: {
        sourceUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        title: "Chapterless Transcript",
        retrievedAt: "2026-09-17T00:00:00.000Z",
        originalHtmlHash: "sha256:rule1",
      },
      blocks: result.blocks,
      footnotes: [],
    });
    expect(deriveToc(article).map((entry) => entry.text)).toEqual(["Top of article"]);
  });

  it("rule 2 — empty/whitespace chapter title: dropped + warning, never invented", () => {
    const result = transcriptToBlocks(
      success([seg("a cue", 5000)], [ch("", 0), ch("   ", 1000), ch("Real", 5000)]),
    );
    const headings = result.blocks.filter((b) => b.kind === "heading");
    expect(headings).toHaveLength(1);
    expect(textOf(headings[0] as { content: { text: string }[] })).toBe("Real");
    expect(result.warnings).toEqual(["2 chapters without a title were omitted"]);
  });

  it("rule 3 — duplicate 0:00 chapter restating the title: dropped + warning", () => {
    const result = transcriptToBlocks(
      success([seg("a cue", 1000)], [ch("Never Gonna Give You Up", 0), ch("never  gonna give you up", 0)]),
    );
    expect(result.blocks.filter((b) => b.kind === "heading")).toHaveLength(0);
    expect(result.warnings).toEqual(["2 chapters duplicating the video title were omitted"]);
  });

  it("rule 3 is exact-normalized — near-title 0:00 chapters are KEPT (never over-drop)", () => {
    // "…(Official Video)" adds words → it does NOT restate the title → kept
    const result = transcriptToBlocks(
      success([seg("a cue", 1000)], [ch("Never Gonna Give You Up (Official Video)", 0)]),
    );
    const headings = result.blocks.filter((b) => b.kind === "heading");
    expect(headings).toHaveLength(1);
    expect(result.warnings).toEqual([]);
  });

  it("rule 3 is title-dependent — a 0:00 chapter with a DIFFERENT title is kept", () => {
    const result = transcriptToBlocks(success([seg("a cue", 1000)], [ch("Intro", 0)]));
    const headings = result.blocks.filter((b) => b.kind === "heading");
    expect(headings).toHaveLength(1);
    expect(result.warnings).toEqual([]);
  });

  it("rule 4 — a chapter starting mid-group breaks the paragraph there; h2 joins the map", () => {
    // three 100-char cues at t=0/1000/2000: the chapter at 1500 lands between
    // the second and third cue → the group [a b] flushes, the h2 emits, and
    // the chapter's first following cue begins the new paragraph
    const a = cue(100, 0);
    const b = cue(100, 2);
    const c = cue(100, 4);
    const result = transcriptToBlocks(
      success([seg(a, 0), seg(b, 1000), seg(c, 2000)], [ch("Mid", 1500)]),
    );
    expect(result.blocks.map((b) => b.kind)).toEqual(["paragraph", "heading", "paragraph"]);
    expect(textOf(result.blocks[0] as { content: { text: string }[] })).toBe(`${a} ${b}`);
    expect(textOf(result.blocks[2] as { content: { text: string }[] })).toBe(c);
  });

  it("rule 4 — a chapter exactly at a segment start breaks BEFORE that segment", () => {
    const a = cue(100, 0);
    const b = cue(100, 2);
    const result = transcriptToBlocks(
      success([seg(a, 0), seg(b, 1000)], [ch("Boundary", 1000)]),
    );
    expect(result.blocks.map((b) => b.kind)).toEqual(["paragraph", "heading", "paragraph"]);
  });

  it("rule 5 — a chapter beyond the last segment (truncated transcript): dropped + warning", () => {
    const result = transcriptToBlocks(
      success([seg("a cue", 0)], [ch("Real", 0), ch("Outro", 999_999)]),
    );
    const headings = result.blocks.filter((b) => b.kind === "heading");
    expect(headings).toHaveLength(1);
    expect(result.warnings).toEqual(["1 chapter past the last caption was omitted"]);
  });
});

describe("block-keyed timestamp anchors (ingestionMeta.transcript.segments)", () => {
  it("maps every paragraph to its first segment's startMs and every h2 to its chapter startMs", () => {
    const a = cue(100, 0);
    const b = cue(100, 2);
    const c = cue(100, 4);
    const d = cue(100, 6);
    const result = transcriptToBlocks(
      success(
        [seg(a, 1000), seg(b, 2000), seg(c, 3000), seg(d, 60_000)],
        [ch("Chapter One", 3000), ch("Chapter Two", 60_000)],
      ),
    );
    // expected stream: p(a b) breaks at C1 (its startMs 3000 arrives with the
    // third cue) → h2(C1) p(c) → C2 at the last cue → h2(C2) p(d)
    expect(result.blocks.map((b) => b.kind)).toEqual(["paragraph", "heading", "paragraph", "heading", "paragraph"]);
    expect(result.anchors).toEqual([
      { blockIndex: 0, startMs: 1000 }, // first paragraph → first segment start
      { blockIndex: 1, startMs: 3000 }, // the chapter h2 participates with its own time
      { blockIndex: 2, startMs: 3000 }, // the chapter break started this group
      { blockIndex: 3, startMs: 60_000 },
      { blockIndex: 4, startMs: 60_000 },
    ]);
  });

  it("anchors are strictly increasing in blockIndex and cover exactly the timestamped blocks", () => {
    const segments: TranscriptSegment[] = [];
    let t = 0;
    for (let i = 0; i < 50; i += 1) {
      segments.push(seg(cue(120, i), t));
      t += 1000;
    }
    const result = transcriptToBlocks(success(segments));
    expect(result.anchors).toHaveLength(result.blocks.length);
    for (let i = 0; i < result.anchors.length; i += 1) {
      expect(result.anchors[i]!.blockIndex).toBe(i);
      if (i > 0) {
        expect(result.anchors[i]!.startMs).toBeGreaterThanOrEqual(result.anchors[i - 1]!.startMs);
      }
    }
  });

  it("timestamps never enter block text (nothing timestamp-bearing reaches the surface)", () => {
    const result = transcriptToBlocks(
      success([seg("words only", 1234)], [ch("Chapter", 0)]),
    );
    const allText = result.blocks
      .map((b) => (b.kind === "paragraph" || b.kind === "heading" ? textOf(b) : ""))
      .join(" ");
    expect(allText).not.toContain("1234");
    expect(allText).toContain("words only");
  });
});
